### PR TITLE
Android sdk code formatting

### PR DESCRIPTION
**Pull request by accurateKevin**
Clean up code snips and update the narrative on transfer Kin transaction

### CODE REVIEW

**Comment by accurateKevin** [comment]
Still working on narrative.

**Comment by andreaKin** [comment]
I edited the paragraph about on boarding again, adding that friendbot also helps developers create accounts, the original text seemed to imply that they are created automatically in Playground.

I also edited one or two of the code snippets, all the others looked good, thank you.

Do you think the "..." is needed in the dependencies code snippet at the very beginning?

**Comment by accurateKevin** [comment]
I removed the '...' from gradle snips.

**Comment by accurateKevin** [comment]
When I just pushed I needed to resolve a merge conflict. I think it was only in the area where I now talk about the two instances of printStackTrace, but please check to make sure I didn't overwrite your edits to onboarding.

**Pull request merged**
